project_id = "misnkzxiahkxmrfinknn"

[functions.analyze-food]
verify_jwt = true

[functions.analyze-food-text]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.generate-insights]
verify_jwt = true